### ISSUE TITLE
Cambio botón 1

### ISSUE THREAD

**Issue by Rosalba2023** [Rosalba2023/calculadora#6]
Realice el cambio del boto 1 a un color azul agua

**Comment by IngRoberth** [comment]
Ya quedo el cambio, adjunto la evidencia @Rosalba2023, se lo mande en una solicitud de extracción.
![image](https://github.com/Rosalba2023/calculadora/assets/137822138/5dff00f3-1afe-49b3-bdd5-bb7e06511ed6)

**Comment by Rosalba2023** [comment]
Bien hecho
